"""Achievement catalog - canonical source of truth for all Discoin achievements.

Each entry defines a badge that the bot can award when a user hits a milestone.
services/achievements.py syncs this catalog into the `badges` table on cog
load so the API (api/v2/routers/users.py) and the in-bot `,achievements`
command render the same list.

Schema of each entry:
    badge_id      - stable id used across DB, API, and code. Never rename.
    name          - short display name.
    description   - one-line description shown in embeds.
    icon          - single emoji.
    category      - grouping used by the browse command.
    requirement   - human-readable trigger description (stored as JSONB).
    reward_usd    - USD paid to wallet on grant.
    sort_order    - display order within its category (ascending).
    secret        - if True, hidden in the catalog until earned.

The `trigger` field in requirement is a LOGICAL label; the bus-event to
trigger-label map lives in services/achievements.py so a single label can
fan in from multiple bus events (e.g. Discord trade + API trade).
"""
from __future__ import annotations

# Categories drive the browse paginator order and heading color.
CATEGORIES: tuple[str, ...] = (
    "getting_started",
    "trading",
    "mining",
    "staking",
    "defi",
    "items",
    "chat",
    "buddy",
    "fishing",
    "dungeon",
    "farming",
    "crafting",
    "auction",
    "gambling",
    "eat",
    "sage",
    "milestone",
)

ACHIEVEMENTS: list[dict] = [
    # Getting started
    {
        "badge_id": "first_step",
        "name": "First Step",
        "description": "Register your wallet and join the economy.",
        "icon": "\U0001F4DD",
        "category": "getting_started",
        "requirement": {"trigger": "register", "count": 1},
        "reward_usd": 25.0,
        "sort_order": 0,
    },
    {
        "badge_id": "daily_regular",
        "name": "Daily Regular",
        "description": "Claim your daily reward 7 times.",
        "icon": "\U0001F4C5",
        "category": "getting_started",
        "requirement": {"trigger": "daily_claimed", "count": 7},
        "reward_usd": 100.0,
        "sort_order": 10,
    },
    {
        "badge_id": "daily_devotee",
        "name": "Daily Devotee",
        "description": "Claim your daily reward 30 times.",
        "icon": "\U0001F4C6",
        "category": "getting_started",
        "requirement": {"trigger": "daily_claimed", "count": 30},
        "reward_usd": 500.0,
        "sort_order": 11,
    },
    {
        "badge_id": "streak_lit",
        "name": "Streak Lit",
        "description": "Claim daily 3 days in a row.",
        "icon": "\U0001F525",
        "category": "getting_started",
        "requirement": {"trigger": "daily_streak", "threshold": 3},
        "reward_usd": 75.0,
        "sort_order": 12,
    },
    {
        "badge_id": "streak_week",
        "name": "Week Warrior",
        "description": "Claim daily 7 days in a row.",
        "icon": "\U0001F5D3",
        "category": "getting_started",
        "requirement": {"trigger": "daily_streak", "threshold": 7},
        "reward_usd": 300.0,
        "sort_order": 13,
    },
    {
        "badge_id": "streak_month",
        "name": "Iron Discipline",
        "description": "Claim daily 30 days in a row.",
        "icon": "\U0001F4AA",
        "category": "getting_started",
        "requirement": {"trigger": "daily_streak", "threshold": 30},
        "reward_usd": 2000.0,
        "sort_order": 14,
    },
    {
        "badge_id": "streak_legend",
        "name": "Unbroken",
        "description": "Claim daily 100 days in a row. No days off.",
        "icon": "\U0001F3C5",
        "category": "getting_started",
        "requirement": {"trigger": "daily_streak", "threshold": 100},
        "reward_usd": 15000.0,
        "sort_order": 15,
    },
    {
        "badge_id": "first_paycheck",
        "name": "First Paycheck",
        "description": "Complete your first shift at a job.",
        "icon": "\U0001F4BC",
        "category": "getting_started",
        "requirement": {"trigger": "work_completed", "count": 1},
        "reward_usd": 25.0,
        "sort_order": 20,
    },
    {
        "badge_id": "hard_worker",
        "name": "Hard Worker",
        "description": "Complete 50 work shifts.",
        "icon": "\U0001F9F0",
        "category": "getting_started",
        "requirement": {"trigger": "work_completed", "count": 50},
        "reward_usd": 300.0,
        "sort_order": 21,
    },

    # Trading
    {
        "badge_id": "first_trade",
        "name": "First Trade",
        "description": "Complete your very first trade.",
        "icon": "\U0001F530",
        "category": "trading",
        "requirement": {"trigger": "trade_executed", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 0,
    },
    {
        "badge_id": "century_trader",
        "name": "Century Trader",
        "description": "Execute 100 trades.",
        "icon": "\U0001F4AF",
        "category": "trading",
        "requirement": {"trigger": "trade_executed", "count": 100},
        "reward_usd": 500.0,
        "sort_order": 10,
    },
    {
        "badge_id": "millennium_trader",
        "name": "Millennium Trader",
        "description": "Execute 1,000 trades.",
        "icon": "\U0001F3C6",
        "category": "trading",
        "requirement": {"trigger": "trade_executed", "count": 1000},
        "reward_usd": 5000.0,
        "sort_order": 11,
    },
    {
        "badge_id": "swapper",
        "name": "Swapper",
        "description": "Use an AMM swap 10 times.",
        "icon": "\U0001F501",
        "category": "trading",
        "requirement": {"trigger": "swap_executed", "count": 10},
        "reward_usd": 150.0,
        "sort_order": 20,
    },

    # Mining
    {
        "badge_id": "first_block",
        "name": "First Block",
        "description": "Earn your first mining payout.",
        "icon": "\U000026CF",
        "category": "mining",
        "requirement": {"trigger": "block_mined", "count": 1},
        "reward_usd": 75.0,
        "sort_order": 0,
    },
    {
        "badge_id": "block_producer",
        "name": "Block Producer",
        "description": "Earn 100 mining payouts.",
        "icon": "\U0001F9F1",
        "category": "mining",
        "requirement": {"trigger": "block_mined", "count": 100},
        "reward_usd": 750.0,
        "sort_order": 10,
    },
    {
        "badge_id": "hashrate_hero",
        "name": "Hashrate Hero",
        "description": "Earn 1,000 mining payouts across all networks.",
        "icon": "\U0001F525",
        "category": "mining",
        "requirement": {"trigger": "block_mined", "count": 1000},
        "reward_usd": 7500.0,
        "sort_order": 11,
    },

    # Staking
    {
        "badge_id": "first_stake",
        "name": "First Stake",
        "description": "Lock your first stake position.",
        "icon": "\U0001F4CC",
        "category": "staking",
        "requirement": {"trigger": "stake_created", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 0,
    },
    {
        "badge_id": "validator",
        "name": "Validator",
        "description": "Register a PoS validator on any network.",
        "icon": "\U0001F6E1",
        "category": "staking",
        "requirement": {"trigger": "validator_registered", "count": 1},
        "reward_usd": 250.0,
        "sort_order": 5,
    },
    {
        "badge_id": "yield_farmer",
        "name": "Yield Farmer",
        "description": "Collect 10 validator reward payouts.",
        "icon": "\U0001F33E",
        "category": "staking",
        "requirement": {"trigger": "stake_reward", "count": 10},
        "reward_usd": 200.0,
        "sort_order": 10,
    },

    # DeFi
    {
        "badge_id": "liquidity_provider",
        "name": "Liquidity Provider",
        "description": "Add liquidity to a pool.",
        "icon": "\U0001F9EA",
        "category": "defi",
        "requirement": {"trigger": "lp_added", "count": 1},
        "reward_usd": 75.0,
        "sort_order": 0,
    },
    {
        "badge_id": "pool_shark",
        "name": "Pool Shark",
        "description": "Add liquidity 5 times in your lifetime.",
        "icon": "\U0001F988",
        "category": "defi",
        "requirement": {"trigger": "lp_added", "count": 5},
        "reward_usd": 400.0,
        "sort_order": 10,
    },
    {
        "badge_id": "saver",
        "name": "Saver",
        "description": "Make your first bank deposit.",
        "icon": "\U0001F3E6",
        "category": "defi",
        "requirement": {"trigger": "bank_deposit", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 20,
    },
    {
        "badge_id": "vault_keeper",
        "name": "Vault Keeper",
        "description": "Make 25 bank deposits.",
        "icon": "\U0001F4B0",
        "category": "defi",
        "requirement": {"trigger": "bank_deposit", "count": 25},
        "reward_usd": 500.0,
        "sort_order": 21,
    },

    # Items (stone level-ups)
    {
        "badge_id": "stone_artisan",
        "name": "Stone Artisan",
        "description": "Level up a stone for the first time.",
        "icon": "\U0001F48E",
        "category": "items",
        "requirement": {"trigger": "stone_leveled", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 0,
    },
    {
        "badge_id": "stone_smith",
        "name": "Stone Smith",
        "description": "Level up stones 10 times total.",
        "icon": "\U0001F528",
        "category": "items",
        "requirement": {"trigger": "stone_leveled", "count": 10},
        "reward_usd": 500.0,
        "sort_order": 10,
    },
    {
        "badge_id": "stone_master",
        "name": "Stone Master",
        "description": "Level up stones 50 times total.",
        "icon": "\U0001F9D9",
        "category": "items",
        "requirement": {"trigger": "stone_leveled", "count": 50},
        "reward_usd": 3000.0,
        "sort_order": 20,
    },
    {
        "badge_id": "stone_legendary",
        "name": "Legendary Forger",
        "description": "Level up stones 200 times. Mythic dedication.",
        "icon": "\U0001F451",
        "category": "items",
        "requirement": {"trigger": "stone_leveled", "count": 200},
        "reward_usd": 12000.0,
        "sort_order": 30,
    },

    # Chat
    {
        "badge_id": "chatty",
        "name": "Chatty",
        "description": "Reach chat level 5.",
        "icon": "\U0001F4AC",
        "category": "chat",
        "requirement": {"trigger": "chat_level_up", "level": 5},
        "reward_usd": 100.0,
        "sort_order": 0,
    },
    {
        "badge_id": "voice_of_the_server",
        "name": "Voice of the Server",
        "description": "Reach chat level 25.",
        "icon": "\U0001F4E3",
        "category": "chat",
        "requirement": {"trigger": "chat_level_up", "level": 25},
        "reward_usd": 1000.0,
        "sort_order": 10,
    },

    # Buddy
    {
        "badge_id": "new_best_friend",
        "name": "New Best Friend",
        "description": "Adopt your first buddy.",
        "icon": "\U0001F436",
        "category": "buddy",
        "requirement": {"trigger": "buddy_adopted", "count": 1},
        "reward_usd": 75.0,
        "sort_order": 0,
    },
    {
        "badge_id": "buddy_champion",
        "name": "Buddy Champion",
        "description": "Win 25 buddy battles.",
        "icon": "\U0001F3C5",
        "category": "buddy",
        "requirement": {"trigger": "buddy_battle_win", "count": 25},
        "reward_usd": 750.0,
        "sort_order": 10,
    },
    {
        "badge_id": "buddy_family",
        "name": "Buddy Family",
        "description": "Adopt 5 buddies over your lifetime.",
        "icon": "\U0001F46A",
        "category": "buddy",
        "requirement": {"trigger": "buddy_adopted", "count": 5},
        "reward_usd": 500.0,
        "sort_order": 20,
    },
    {
        "badge_id": "buddy_legend",
        "name": "Buddy Legend",
        "description": "Win 100 buddy battles.",
        "icon": "\U0001F989",
        "category": "buddy",
        "requirement": {"trigger": "buddy_battle_win", "count": 100},
        "reward_usd": 2500.0,
        "sort_order": 30,
    },
    {
        "badge_id": "buddy_dynasty",
        "name": "Buddy Dynasty",
        "description": "Win 500 buddy battles. A name whispered in the shelter.",
        "icon": "\U0001F409",
        "category": "buddy",
        "requirement": {"trigger": "buddy_battle_win", "count": 500},
        "reward_usd": 15000.0,
        "sort_order": 40,
    },
    {
        "badge_id": "buddy_shelter_savior",
        "name": "Shelter Savior",
        "description": "Adopt 20 buddies, rescuing the shelter many times over.",
        "icon": "\U0001F3E1",
        "category": "buddy",
        "requirement": {"trigger": "buddy_adopted", "count": 20},
        "reward_usd": 3500.0,
        "sort_order": 50,
    },

    # Fishing
    {
        "badge_id": "first_cast",
        "name": "First Cast",
        "description": "Land your first fish.",
        "icon": "\U0001F3A3",
        "category": "fishing",
        "requirement": {"trigger": "fish_caught", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 0,
    },
    {
        "badge_id": "weekend_angler",
        "name": "Weekend Angler",
        "description": "Catch 50 fish.",
        "icon": "\U0001F420",
        "category": "fishing",
        "requirement": {"trigger": "fish_caught", "count": 50},
        "reward_usd": 500.0,
        "sort_order": 10,
    },
    {
        "badge_id": "tackle_master",
        "name": "Tackle Master",
        "description": "Catch 250 fish. Your forearms are jealous.",
        "icon": "\U0001F38B",
        "category": "fishing",
        "requirement": {"trigger": "fish_caught", "count": 250},
        "reward_usd": 2500.0,
        "sort_order": 20,
    },
    {
        "badge_id": "trophy_hunter",
        "name": "Trophy Hunter",
        "description": "Land a Legendary fish.",
        "icon": "\U0001F3C6",
        "category": "fishing",
        "requirement": {"trigger": "fish_legendary", "count": 1},
        "reward_usd": 5000.0,
        "sort_order": 30,
    },
    {
        "badge_id": "kraken_slayer",
        "name": "Kraken Slayer",
        "description": "Catch 5 Legendary fish.",
        "icon": "\U0001F40B",
        "category": "fishing",
        "requirement": {"trigger": "fish_legendary", "count": 5},
        "reward_usd": 25000.0,
        "sort_order": 40,
    },
    {
        "badge_id": "ocean_hatchling",
        "name": "Ocean Hatchling",
        "description": "Hatch a buddy from a fishing egg.",
        "icon": "\U0001F95A",
        "category": "fishing",
        "requirement": {"trigger": "fish_buddy_egg", "count": 1},
        "reward_usd": 1500.0,
        "sort_order": 50,
    },
    {
        "badge_id": "abyss_walker",
        "name": "Abyss Walker",
        "description": "Catch 1,000 fish.",
        "icon": "\U0001F30A",
        "category": "fishing",
        "requirement": {"trigger": "fish_caught", "count": 1000},
        "reward_usd": 15_000.0,
        "sort_order": 60,
    },
    {
        "badge_id": "leviathan_keeper",
        "name": "Leviathan Keeper",
        "description": "Catch 25 Legendary fish.",
        "icon": "\U0001F432",
        "category": "fishing",
        "requirement": {"trigger": "fish_legendary", "count": 25},
        "reward_usd": 100_000.0,
        "sort_order": 70,
    },
    {
        "badge_id": "first_swap",
        "name": "First Swap",
        "description": "Burn LURE for REEL once -- the network coin is yours now.",
        "icon": "\U0001F501",
        "category": "fishing",
        "requirement": {"trigger": "fish_lure_swap", "count": 1},
        "reward_usd": 250.0,
        "sort_order": 80,
    },
    {
        "badge_id": "stake_holder",
        "name": "Stake Holder",
        "description": "Stake LURE 5 times. Patience pays.",
        "icon": "\U0001F510",
        "category": "fishing",
        "requirement": {"trigger": "fish_lure_stake", "count": 5},
        "reward_usd": 1_000.0,
        "sort_order": 90,
    },
    {
        "badge_id": "first_cashout",
        "name": "First Cashout",
        "description": "Burn REEL for USD once. Real money for fake fish.",
        "icon": "\U0001F4B5",
        "category": "fishing",
        "requirement": {"trigger": "fish_reel_cashout", "count": 1},
        "reward_usd": 500.0,
        "sort_order": 100,
    },
    {
        "badge_id": "tide_baron",
        "name": "Tide Baron",
        "description": "Cash out REEL 25 times. The network funds your retirement.",
        "icon": "\U0001F451",
        "category": "fishing",
        "requirement": {"trigger": "fish_reel_cashout", "count": 25},
        "reward_usd": 25_000.0,
        "sort_order": 110,
    },
    {
        "badge_id": "wild_first_blood",
        "name": "First Blood",
        "description": "Win your first wild-buddy battle from a cast.",
        "icon": "\U00002694",
        "category": "fishing",
        "requirement": {"trigger": "fish_wild_battle_won", "count": 1},
        "reward_usd": 1_000.0,
        "sort_order": 120,
    },
    {
        "badge_id": "wild_brawler",
        "name": "Deep Water Brawler",
        "description": "Win 25 wild-buddy battles from casts.",
        "icon": "\U0001F94A",
        "category": "fishing",
        "requirement": {"trigger": "fish_wild_battle_won", "count": 25},
        "reward_usd": 15_000.0,
        "sort_order": 130,
    },
    {
        "badge_id": "wild_apex",
        "name": "Apex Angler",
        "description": "Win 100 wild-buddy battles. The wild fears you now.",
        "icon": "\U0001F451",
        "category": "fishing",
        "requirement": {"trigger": "fish_wild_battle_won", "count": 100},
        "reward_usd": 75_000.0,
        "sort_order": 140,
    },
    {
        "badge_id": "wild_tamer",
        "name": "Wild Tamer",
        "description": "Capture a wild aquatic buddy after defeating it.",
        "icon": "\U0001F578",
        "category": "fishing",
        "requirement": {"trigger": "fish_wild_buddy_captured", "count": 1},
        "reward_usd": 2_500.0,
        "sort_order": 150,
    },
    {
        "badge_id": "wild_collector",
        "name": "Aquarium Curator",
        "description": "Capture 10 wild buddies from cast battles.",
        "icon": "\U0001F41F",
        "category": "fishing",
        "requirement": {"trigger": "fish_wild_buddy_captured", "count": 10},
        "reward_usd": 30_000.0,
        "sort_order": 160,
    },

    # Gambling
    {
        "badge_id": "degen",
        "name": "Degen",
        "description": "Play 50 games.",
        "icon": "\U0001F3B0",
        "category": "gambling",
        "requirement": {"trigger": "gamble_play", "count": 50},
        "reward_usd": 250.0,
        "sort_order": 0,
    },
    {
        "badge_id": "lucky_streak",
        "name": "Lucky Streak",
        "description": "Win 10 games.",
        "icon": "\U0001F340",
        "category": "gambling",
        "requirement": {"trigger": "gamble_win", "count": 10},
        "reward_usd": 200.0,
        "sort_order": 10,
    },

    # Eat the Rich
    {
        "badge_id": "first_exploit",
        "name": "First Bite",
        "description": "Make your first attempt to eat the rich.",
        "icon": "\U0001F37D",
        "category": "eat",
        "requirement": {"trigger": "exploit_run", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 0,
    },
    {
        "badge_id": "robin_hood",
        "name": "Robin Hood",
        "description": "Eat the rich 10 times.",
        "icon": "\U0001F3F9",
        "category": "eat",
        "requirement": {"trigger": "exploit_win", "count": 10},
        "reward_usd": 500.0,
        "sort_order": 10,
    },

    # Milestones (threshold triggers -- fire once net worth crosses the bar)
    {
        "badge_id": "millionaire",
        "name": "Millionaire",
        "description": "Reach a net worth of $1,000,000.",
        "icon": "\U0001F4B0",
        "category": "milestone",
        "requirement": {"trigger": "net_worth", "threshold": 1_000_000},
        "reward_usd": 1000.0,
        "sort_order": 0,
    },
    {
        "badge_id": "whale",
        "name": "Whale",
        "description": "Reach a net worth of $100,000,000.",
        "icon": "\U0001F40B",
        "category": "milestone",
        "requirement": {"trigger": "net_worth", "threshold": 100_000_000},
        "reward_usd": 25_000.0,
        "sort_order": 10,
    },

    # Dungeon (Delve crawler) -- triggers fired by services/dungeon.py
    {
        "badge_id": "first_descent",
        "name": "First Descent",
        "description": "Start your first dungeon run.",
        "icon": "\U0001F6AA",
        "category": "dungeon",
        "requirement": {"trigger": "delve_run_start", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 0,
    },
    {
        "badge_id": "first_kill",
        "name": "First Blood",
        "description": "Slay your first dungeon mob.",
        "icon": "\U00002694",
        "category": "dungeon",
        "requirement": {"trigger": "delve_kill", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 10,
    },
    {
        "badge_id": "delve_century",
        "name": "Centurion",
        "description": "Slay 100 dungeon mobs.",
        "icon": "\U0001F5E1",
        "category": "dungeon",
        "requirement": {"trigger": "delve_kill", "count": 100},
        "reward_usd": 1000.0,
        "sort_order": 20,
    },
    {
        "badge_id": "delve_butcher",
        "name": "Butcher of the Deep",
        "description": "Slay 1,000 dungeon mobs.",
        "icon": "\U0001FA93",
        "category": "dungeon",
        "requirement": {"trigger": "delve_kill", "count": 1000},
        "reward_usd": 10_000.0,
        "sort_order": 30,
    },
    {
        "badge_id": "first_capture",
        "name": "Soft Touch",
        "description": "Capture your first dungeon buddy.",
        "icon": "\U0001F9F2",
        "category": "dungeon",
        "requirement": {"trigger": "delve_capture", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 40,
    },
    {
        "badge_id": "beastmaster",
        "name": "Beastmaster",
        "description": "Capture 25 dungeon buddies.",
        "icon": "\U0001F43E",
        "category": "dungeon",
        "requirement": {"trigger": "delve_capture", "count": 25},
        "reward_usd": 2500.0,
        "sort_order": 50,
    },
    {
        "badge_id": "first_boss",
        "name": "Slayer",
        "description": "Defeat your first dungeon boss.",
        "icon": "\U0001F47E",
        "category": "dungeon",
        "requirement": {"trigger": "delve_boss_kill", "count": 1},
        "reward_usd": 750.0,
        "sort_order": 60,
    },
    {
        "badge_id": "boss_circuit",
        "name": "Boss Circuit",
        "description": "Defeat each of the four bosses at least once.",
        "icon": "\U0001F451",
        "category": "dungeon",
        "requirement": {"trigger": "delve_boss_kill", "count": 4},
        "reward_usd": 5000.0,
        "sort_order": 65,
    },
    {
        "badge_id": "ancient_one_slain",
        "name": "Conqueror",
        "description": "Defeat The Archon on Floor 40 -- the dungeon's true final boss.",
        "icon": "\U0001F3C5",
        "category": "dungeon",
        "requirement": {"trigger": "delve_clear_run", "count": 1},
        "reward_usd": 25_000.0,
        "sort_order": 70,
    },
    {
        "badge_id": "copper_collector",
        "name": "Copper Collector",
        "description": "Mine 5,000 COPPER.",
        "icon": "\U0001FA99",
        "category": "dungeon",
        "requirement": {"trigger": "delve_mined_copper", "threshold": 5000},
        "reward_usd": 500.0,
        "sort_order": 80,
    },
    {
        "badge_id": "silver_hoard",
        "name": "Silver Hoard",
        "description": "Mine 1,000 SILVER.",
        "icon": "\U0001F948",
        "category": "dungeon",
        "requirement": {"trigger": "delve_mined_silver", "threshold": 1000},
        "reward_usd": 1500.0,
        "sort_order": 90,
    },
    {
        "badge_id": "gold_baron",
        "name": "Gold Baron",
        "description": "Mine 200 GOLD.",
        "icon": "\U0001F947",
        "category": "dungeon",
        "requirement": {"trigger": "delve_mined_gold", "threshold": 200},
        "reward_usd": 5000.0,
        "sort_order": 100,
    },
    {
        "badge_id": "rune_smith",
        "name": "Rune Smith",
        "description": "Earn 1,000 RUNE total (mining + staking + drops).",
        "icon": "\U0001FAA8",
        "category": "dungeon",
        "requirement": {"trigger": "delve_rune_earned", "threshold": 1000},
        "reward_usd": 2500.0,
        "sort_order": 110,
    },

    # Farming -- triggers fired by services/farming.py
    {
        "badge_id": "first_seed",
        "name": "First Seed",
        "description": "Plant your first seed.",
        "icon": "\U0001F331",
        "category": "farming",
        "requirement": {"trigger": "farm_plant", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 0,
    },
    {
        "badge_id": "green_thumb",
        "name": "Green Thumb",
        "description": "Harvest your first crop.",
        "icon": "\U0001F33E",
        "category": "farming",
        "requirement": {"trigger": "farm_harvest", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 10,
    },
    {
        "badge_id": "weekend_farmer",
        "name": "Weekend Farmer",
        "description": "Harvest 100 crops.",
        "icon": "\U0001F69C",
        "category": "farming",
        "requirement": {"trigger": "farm_harvest", "count": 100},
        "reward_usd": 1000.0,
        "sort_order": 20,
    },
    {
        "badge_id": "master_farmer",
        "name": "Master Farmer",
        "description": "Harvest 1,000 crops.",
        "icon": "\U0001F468‍\U0001F33E",
        "category": "farming",
        "requirement": {"trigger": "farm_harvest", "count": 1000},
        "reward_usd": 10000.0,
        "sort_order": 30,
    },
    {
        "badge_id": "golden_harvest",
        "name": "Golden Harvest",
        "description": "Pull a golden-tier crop (golden_apple, ambrosia, or world_tree).",
        "icon": "\U0001F34E",
        "category": "farming",
        "requirement": {"trigger": "farm_golden_harvest", "count": 1},
        "reward_usd": 2500.0,
        "sort_order": 40,
    },
    {
        "badge_id": "bumper_crop",
        "name": "Bumper Crop",
        "description": "Pull your first legendary harvest.",
        "icon": "\U0001F3C6",
        "category": "farming",
        "requirement": {"trigger": "farm_legendary_harvest", "count": 1},
        "reward_usd": 5000.0,
        "sort_order": 50,
    },
    {
        "badge_id": "seasoned_grower",
        "name": "Seasoned Grower",
        "description": "Pull 10 legendary harvests.",
        "icon": "\U0001F33B",
        "category": "farming",
        "requirement": {"trigger": "farm_legendary_harvest", "count": 10},
        "reward_usd": 25000.0,
        "sort_order": 60,
    },
    {
        "badge_id": "crop_circle",
        "name": "Crop Circle",
        "description": "Harvest at least one of every crop type.",
        "icon": "\U0001F6F8",
        "category": "farming",
        "requirement": {"trigger": "farm_all_crops", "count": 1},
        "reward_usd": 15000.0,
        "sort_order": 70,
    },
    {
        "badge_id": "master_chef",
        "name": "Master Chef",
        "description": "Process 50 recipes.",
        "icon": "\U0001F35E",
        "category": "farming",
        "requirement": {"trigger": "farm_recipe_made", "count": 50},
        "reward_usd": 2500.0,
        "sort_order": 80,
    },
    {
        "badge_id": "pest_control",
        "name": "Pest Control",
        "description": "Kill your first farm pest.",
        "icon": "\U0001F997",
        "category": "farming",
        "requirement": {"trigger": "farm_pest_kill", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 90,
    },
    {
        "badge_id": "blight_slayer",
        "name": "Blight Slayer",
        "description": "Defeat the_blight, the boss pest.",
        "icon": "\U0001F47B",
        "category": "farming",
        "requirement": {"trigger": "farm_boss_pest_kill", "count": 1},
        "reward_usd": 5000.0,
        "sort_order": 100,
    },
    {
        "badge_id": "plot_baron",
        "name": "Plot Baron",
        "description": "Reach plot tier 9.",
        "icon": "\U0001F3E1",
        "category": "farming",
        "requirement": {"trigger": "farm_plot_upgraded", "threshold": 9},
        "reward_usd": 25000.0,
        "sort_order": 110,
    },
    {
        "badge_id": "seed_baron",
        "name": "Seed Baron",
        "description": "Stake SEED 5 times.",
        "icon": "\U0001F4B1",
        "category": "farming",
        "requirement": {"trigger": "farm_seed_stake", "count": 5},
        "reward_usd": 500.0,
        "sort_order": 120,
    },
    {
        "badge_id": "first_cashout_farm",
        "name": "First Cashout (Farm)",
        "description": "Cash out HRV to USD for the first time.",
        "icon": "\U0001F4B5",
        "category": "farming",
        "requirement": {"trigger": "farm_hrv_cashout", "count": 1},
        "reward_usd": 250.0,
        "sort_order": 130,
    },
    # ── Crafting (Forge Network) ────────────────────────────────────────
    {
        "badge_id": "first_craft",
        "name": "Smith Apprentice",
        "description": "Make your first crafted item with `,craft make`.",
        "icon": "\U0001F528",
        "category": "crafting",
        "requirement": {"trigger": "craft_made", "count": 1},
        "reward_usd": 50.0,
        "sort_order": 0,
    },
    {
        "badge_id": "craft_journeyman",
        "name": "Forge Journeyman",
        "description": "Complete 25 crafts.",
        "icon": "\U0001F528",
        "category": "crafting",
        "requirement": {"trigger": "craft_made", "count": 25},
        "reward_usd": 250.0,
        "sort_order": 10,
    },
    {
        "badge_id": "craft_master",
        "name": "Forge Master",
        "description": "Complete 250 crafts.",
        "icon": "\U0001F528",
        "category": "crafting",
        "requirement": {"trigger": "craft_made", "count": 250},
        "reward_usd": 2500.0,
        "sort_order": 20,
    },
    {
        "badge_id": "craft_artisan",
        "name": "Master Artisan",
        "description": "Complete 1,000 crafts.",
        "icon": "\U0001F528",
        "category": "crafting",
        "requirement": {"trigger": "craft_made", "count": 1_000},
        "reward_usd": 10_000.0,
        "sort_order": 30,
    },
    {
        "badge_id": "craft_legendary",
        "name": "Legendary Smith",
        "description": "Craft a legendary recipe.",
        "icon": "\U00002728",
        "category": "crafting",
        "requirement": {"trigger": "craft_legendary", "count": 1},
        "reward_usd": 5_000.0,
        "sort_order": 40,
    },
    {
        "badge_id": "first_apply_craft",
        "name": "From Forge to Field",
        "description": "Apply a crafted item back into a game with `,craft apply`.",
        "icon": "\U0001F503",
        "category": "crafting",
        "requirement": {"trigger": "craft_applied", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 50,
    },
    {
        "badge_id": "craft_ingot_burner",
        "name": "INGOT Burner",
        "description": "Burn INGOT to FORGE 5 times via `,craft swap`.",
        "icon": "\U0001F525",
        "category": "crafting",
        "requirement": {"trigger": "craft_ingot_swap", "count": 5},
        "reward_usd": 500.0,
        "sort_order": 60,
    },
    {
        "badge_id": "first_cashout_craft",
        "name": "First Cashout (Forge)",
        "description": "Cash out FORGE to USD for the first time.",
        "icon": "\U0001F4B5",
        "category": "crafting",
        "requirement": {"trigger": "craft_forge_cashout", "count": 1},
        "reward_usd": 250.0,
        "sort_order": 70,
    },
    # ── Dungeon wild-buddy battles ──────────────────────────────────────
    {
        "badge_id": "first_wild_battle_delve",
        "name": "Cave Brawler",
        "description": "Win your first wild-buddy battle in a delve.",
        "icon": "\U0001F4AB",
        "category": "dungeon",
        "requirement": {"trigger": "delve_wild_battle_won", "count": 1},
        "reward_usd": 200.0,
        "sort_order": 200,
    },
    {
        "badge_id": "wild_battle_streak_delve",
        "name": "Den Crusher",
        "description": "Win 25 wild-buddy battles in delves.",
        "icon": "\U0001F4AB",
        "category": "dungeon",
        "requirement": {"trigger": "delve_wild_battle_won", "count": 25},
        "reward_usd": 2000.0,
        "sort_order": 210,
    },
    {
        "badge_id": "wild_capture_delve",
        "name": "Cave Tamer",
        "description": "Capture a wild buddy in a delve.",
        "icon": "\U0001F49E",
        "category": "dungeon",
        "requirement": {"trigger": "delve_wild_buddy_captured", "count": 1},
        "reward_usd": 500.0,
        "sort_order": 220,
    },
    # ── Buddy Network arena ─────────────────────────────────────────────
    # Tier-bound badges so the achievement screen mirrors the arena's tier
    # ladder (Bronze -> Diamond). Reward USD scales with the tier so the
    # economy doesn't dump payout on the easy ranks.
    {
        "badge_id": "arena_bronze",
        "name": "Bronze Arena Brawler",
        "description": "Win your first Buddy Network arena fight.",
        "icon": "\U0001F949",
        "category": "buddy",
        "requirement": {"trigger": "buddy_arena_won", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 100,
    },
    {
        "badge_id": "arena_silver",
        "name": "Silver Arena Veteran",
        "description": "Win 10 arena fights (Silver tier).",
        "icon": "\U0001F948",
        "category": "buddy",
        "requirement": {"trigger": "buddy_arena_won", "count": 10},
        "reward_usd": 500.0,
        "sort_order": 110,
    },
    {
        "badge_id": "arena_gold",
        "name": "Gold Arena Champion",
        "description": "Win 50 arena fights (Gold tier).",
        "icon": "\U0001F947",
        "category": "buddy",
        "requirement": {"trigger": "buddy_arena_won", "count": 50},
        "reward_usd": 2000.0,
        "sort_order": 120,
    },
    {
        "badge_id": "arena_platinum",
        "name": "Platinum Arena Master",
        "description": "Win 150 arena fights (Platinum tier).",
        "icon": "\U0001F4A0",
        "category": "buddy",
        "requirement": {"trigger": "buddy_arena_won", "count": 150},
        "reward_usd": 7500.0,
        "sort_order": 130,
    },
    {
        "badge_id": "arena_diamond",
        "name": "Diamond Arena Legend",
        "description": "Win 500 arena fights (Diamond tier).",
        "icon": "\U0001F48E",
        "category": "buddy",
        "requirement": {"trigger": "buddy_arena_won", "count": 500},
        "reward_usd": 25000.0,
        "sort_order": 140,
    },
    {
        "badge_id": "buddy_battles_first",
        "name": "First Blood",
        "description": "Win your first buddy battle (any surface counts).",
        "icon": "\U0001FA78",
        "category": "buddy",
        "requirement": {"trigger": "buddy_battle_win", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 5,
    },
    # ── Buddy storage ("computer") ───────────────────────────────────────
    {
        "badge_id": "buddy_first_store",
        "name": "Pack It Up",
        "description": "Stash your first buddy in storage with `,buddy store`.",
        "icon": "\U0001F4E6",
        "category": "buddy",
        "requirement": {"trigger": "buddy_stored", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 200,
    },
    {
        "badge_id": "buddy_collector",
        "name": "Buddy Collector",
        "description": "Have 10 different buddies stored at once.",
        "icon": "\U0001F4DA",
        "category": "buddy",
        "requirement": {"trigger": "buddy_storage_count", "count": 10},
        "reward_usd": 1000.0,
        "sort_order": 210,
    },
    # ── Buddy nest / breeding ────────────────────────────────────────────
    # Internal trigger label kept as ``daycare_egg_collected`` for schema
    # stability; the player-facing name is "nest" everywhere now.
    {
        "badge_id": "daycare_first_egg",
        "name": "First Hatchling",
        "description": "Collect your first egg from the nest.",
        "icon": "\U0001F423",
        "category": "buddy",
        "requirement": {"trigger": "daycare_egg_collected", "count": 1},
        "reward_usd": 250.0,
        "sort_order": 220,
    },
    {
        "badge_id": "daycare_breeder",
        "name": "Bonded Breeder",
        "description": "Collect 10 nest eggs.",
        "icon": "\U0001F423",
        "category": "buddy",
        "requirement": {"trigger": "daycare_egg_collected", "count": 10},
        "reward_usd": 2500.0,
        "sort_order": 230,
    },
    # ── Crafting specialties ─────────────────────────────────────────────
    {
        "badge_id": "specialty_smithing_10",
        "name": "Apprentice Smith",
        "description": "Reach Smithing level 10.",
        "icon": "\U0001F528",
        "category": "crafting",
        "requirement": {"trigger": "specialty_level_smithing", "count": 10},
        "reward_usd": 500.0,
        "sort_order": 100,
    },
    {
        "badge_id": "specialty_alchemy_10",
        "name": "Apprentice Alchemist",
        "description": "Reach Alchemy level 10.",
        "icon": "\U0001F9EA",
        "category": "crafting",
        "requirement": {"trigger": "specialty_level_alchemy", "count": 10},
        "reward_usd": 500.0,
        "sort_order": 110,
    },
    {
        "badge_id": "specialty_cooking_10",
        "name": "Apprentice Cook",
        "description": "Reach Cooking level 10.",
        "icon": "\U0001F35E",
        "category": "crafting",
        "requirement": {"trigger": "specialty_level_cooking", "count": 10},
        "reward_usd": 500.0,
        "sort_order": 120,
    },
    {
        "badge_id": "specialty_fletching_10",
        "name": "Apprentice Fletcher",
        "description": "Reach Fletching level 10.",
        "icon": "\U0001FAB1",
        "category": "crafting",
        "requirement": {"trigger": "specialty_level_fletching", "count": 10},
        "reward_usd": 500.0,
        "sort_order": 130,
    },
    {
        "badge_id": "specialty_tinkering_10",
        "name": "Apprentice Tinker",
        "description": "Reach Tinkering level 10.",
        "icon": "\U0001F9F0",
        "category": "crafting",
        "requirement": {"trigger": "specialty_level_tinkering", "count": 10},
        "reward_usd": 500.0,
        "sort_order": 140,
    },
    {
        "badge_id": "specialty_renaissance",
        "name": "Renaissance Crafter",
        "description": "Reach level 10 in every crafting specialty.",
        "icon": "\U0001F3DB",
        "category": "crafting",
        "requirement": {"trigger": "specialty_renaissance", "count": 1},
        "reward_usd": 5_000.0,
        "sort_order": 150,
    },
    # ── Wild-buddy zone diversity ────────────────────────────────────────
    {
        "badge_id": "wild_zone_diverse",
        "name": "Habitat Hunter",
        "description": "Win wild buddy battles in 5 different zones.",
        "icon": "\U0001F30F",
        "category": "buddy",
        "requirement": {"trigger": "wild_zone_diversity", "count": 5},
        "reward_usd": 1000.0,
        "sort_order": 240,
    },
    # ── Auction House ────────────────────────────────────────────────────
    {
        "badge_id": "ah_first_listing",
        "name": "Open for Business",
        "description": "List your first item on the auction house.",
        "icon": "\U0001F3DB",
        "category": "auction",
        "requirement": {"trigger": "ah_listing_created", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 10,
    },
    {
        "badge_id": "ah_first_sale",
        "name": "First Buck",
        "description": "Settle your first sale on the auction house.",
        "icon": "\U0001F4B0",
        "category": "auction",
        "requirement": {"trigger": "ah_sale_settled", "count": 1},
        "reward_usd": 250.0,
        "sort_order": 20,
    },
    {
        "badge_id": "ah_first_purchase",
        "name": "Window Shopper",
        "description": "Buy your first item on the auction house.",
        "icon": "\U0001F6CD",
        "category": "auction",
        "requirement": {"trigger": "ah_purchase_settled", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 30,
    },
    {
        "badge_id": "ah_cross_currency",
        "name": "Currency Arbitrageur",
        "description": "Buy a listing using a currency other than the one it was listed in.",
        "icon": "\U0001F501",
        "category": "auction",
        "requirement": {"trigger": "ah_cross_currency_buy", "count": 1},
        "reward_usd": 200.0,
        "sort_order": 40,
    },
    {
        "badge_id": "ah_seller_volume_100",
        "name": "Seasoned Seller",
        "description": "Settle 100 sales on the auction house.",
        "icon": "\U0001F3F7",
        "category": "auction",
        "requirement": {"trigger": "ah_sale_settled", "count": 100},
        "reward_usd": 5000.0,
        "sort_order": 50,
    },

    # Expeditions: timed buddy-driven runs (services/expeditions.py).
    # Bumped on the bus events emitted by ,expedition send / collect.
    {
        "badge_id": "expedition_first",
        "name": "First Steps",
        "description": "Complete your first buddy expedition.",
        "icon": "\U0001F392",
        "category": "buddy",
        "requirement": {"trigger": "expedition_collected", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 60,
    },
    {
        "badge_id": "expedition_10",
        "name": "Trail Blazer",
        "description": "Complete 10 buddy expeditions.",
        "icon": "\U0001F392",
        "category": "buddy",
        "requirement": {"trigger": "expedition_collected", "count": 10},
        "reward_usd": 500.0,
        "sort_order": 61,
    },
    {
        "badge_id": "expedition_50",
        "name": "Career Adventurer",
        "description": "Complete 50 buddy expeditions.",
        "icon": "\U0001F30E",
        "category": "buddy",
        "requirement": {"trigger": "expedition_collected", "count": 50},
        "reward_usd": 3000.0,
        "sort_order": 62,
    },
    {
        "badge_id": "expedition_forest",
        "name": "Forest Friend",
        "description": "Complete an expedition to the Whispering Forest.",
        "icon": "\U0001F332",
        "category": "buddy",
        "requirement": {"trigger": "expedition_collected_forest", "count": 1},
        "reward_usd": 150.0,
        "sort_order": 63,
    },
    {
        "badge_id": "expedition_reef",
        "name": "Reefwalker",
        "description": "Complete an expedition to the Coral Reef.",
        "icon": "\U0001FAB8",
        "category": "buddy",
        "requirement": {"trigger": "expedition_collected_reef", "count": 1},
        "reward_usd": 200.0,
        "sort_order": 64,
    },
    {
        "badge_id": "expedition_mine",
        "name": "Cave Crawler",
        "description": "Complete an expedition to the Forgotten Mine.",
        "icon": "\U000026CF",
        "category": "buddy",
        "requirement": {"trigger": "expedition_collected_mine", "count": 1},
        "reward_usd": 300.0,
        "sort_order": 65,
    },
    {
        "badge_id": "expedition_ruins",
        "name": "Ruin Reader",
        "description": "Complete an expedition to the Ancient Ruins.",
        "icon": "\U0001F3DB",
        "category": "buddy",
        "requirement": {"trigger": "expedition_collected_ruins", "count": 1},
        "reward_usd": 500.0,
        "sort_order": 66,
    },

    # ── Class progression badges (added with archer + druid + reroll) ────
    # Class-specific triggers (e.g. delve_class_picked_archer) are fanned
    # out alongside the generic delve_class_picked from set_class /
    # reroll_class so the per-class counters increment without the bus
    # needing payload-aware filters.
    {
        "badge_id": "class_archer_pick",
        "name": "Apprentice Archer",
        "description": "Pick the Archer class for the first time.",
        "icon": "\U0001F3F9",
        "category": "dungeon",
        "requirement": {"trigger": "delve_class_picked_archer", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 100,
    },
    {
        "badge_id": "class_druid_pick",
        "name": "Apprentice Druid",
        "description": "Pick the Druid class for the first time.",
        "icon": "\U0001F33F",
        "category": "dungeon",
        "requirement": {"trigger": "delve_class_picked_druid", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 101,
    },
    {
        "badge_id": "archer_volley_25",
        "name": "Volley Master",
        "description": "Cast Volley 25 times.",
        "icon": "\U0001F3F9",
        "category": "dungeon",
        "requirement": {"trigger": "delve_skill_volley", "count": 25},
        "reward_usd": 1500.0,
        "sort_order": 110,
    },
    {
        "badge_id": "druid_wildshape_25",
        "name": "Beast Speaker",
        "description": "Trigger Wildshape 25 times.",
        "icon": "\U0001F43B",
        "category": "dungeon",
        "requirement": {"trigger": "delve_skill_wildshape", "count": 25},
        "reward_usd": 1500.0,
        "sort_order": 111,
    },
    {
        "badge_id": "delve_stat_max",
        "name": "Min-Maxer",
        "description": "Spend 50 total delve stat points.",
        "icon": "\U0001F4CA",
        "category": "dungeon",
        "requirement": {"trigger": "delve_stat_spent", "count": 50},
        "reward_usd": 1500.0,
        "sort_order": 120,
    },
    {
        "badge_id": "class_chameleon",
        "name": "Class Chameleon",
        "description": "Reroll your delve class for the first time.",
        "icon": "\U0001F504",
        "category": "dungeon",
        "requirement": {"trigger": "delve_class_reroll", "count": 1},
        "reward_usd": 250.0,
        "sort_order": 121,
    },
    {
        "badge_id": "class_chameleon_5",
        "name": "Identity Crisis",
        "description": "Reroll your delve class 5 times.",
        "icon": "\U0001F500",
        "category": "dungeon",
        "requirement": {"trigger": "delve_class_reroll", "count": 5},
        "reward_usd": 2500.0,
        "sort_order": 122,
    },
    {
        "badge_id": "lv10_warrior",
        "name": "Iron Veteran",
        "description": "Reach Lv. 10 as a Warrior.",
        "icon": "\U00002694",
        "category": "dungeon",
        "requirement": {"trigger": "delve_class_lv10_warrior", "count": 1},
        "reward_usd": 600.0,
        "sort_order": 130,
    },
    {
        "badge_id": "lv10_mage",
        "name": "Channeler",
        "description": "Reach Lv. 10 as a Mage.",
        "icon": "\U0001F9D9",
        "category": "dungeon",
        "requirement": {"trigger": "delve_class_lv10_mage", "count": 1},
        "reward_usd": 600.0,
        "sort_order": 131,
    },
    {
        "badge_id": "lv10_rogue",
        "name": "Shadowstep",
        "description": "Reach Lv. 10 as a Rogue.",
        "icon": "\U0001F5E1",
        "category": "dungeon",
        "requirement": {"trigger": "delve_class_lv10_rogue", "count": 1},
        "reward_usd": 600.0,
        "sort_order": 132,
    },
    {
        "badge_id": "lv10_archer",
        "name": "Sharpshooter",
        "description": "Reach Lv. 10 as an Archer.",
        "icon": "\U0001F3F9",
        "category": "dungeon",
        "requirement": {"trigger": "delve_class_lv10_archer", "count": 1},
        "reward_usd": 600.0,
        "sort_order": 133,
    },
    {
        "badge_id": "lv10_druid",
        "name": "Forest Walker",
        "description": "Reach Lv. 10 as a Druid.",
        "icon": "\U0001F33F",
        "category": "dungeon",
        "requirement": {"trigger": "delve_class_lv10_druid", "count": 1},
        "reward_usd": 600.0,
        "sort_order": 134,
    },
    # ──────────────────────────────────────────────────────────────────────
    # Overhaul achievements -- farming combos, arena PvP, fishing monsters
    # ──────────────────────────────────────────────────────────────────────
    {
        "badge_id": "farm_combo_3",
        "name": "Three In A Row",
        "description": "Chain a 3-step harvest combo.",
        "icon": "\U0001F33E",
        "category": "farming",
        "requirement": {"trigger": "farm_combo_3", "count": 1},
        "reward_usd": 150.0,
        "sort_order": 200,
    },
    {
        "badge_id": "farm_combo_5",
        "name": "Five In A Row",
        "description": "Chain a 5-step harvest combo.",
        "icon": "\U0001F33E",
        "category": "farming",
        "requirement": {"trigger": "farm_combo_5", "count": 1},
        "reward_usd": 500.0,
        "sort_order": 201,
    },
    {
        "badge_id": "farm_combo_legend",
        "name": "Harvest Maestro",
        "description": "Reach a 6-step harvest combo.",
        "icon": "\U0001F31F",
        "category": "farming",
        "requirement": {"trigger": "farm_combo_legend", "count": 1},
        "reward_usd": 1500.0,
        "sort_order": 202,
    },
    {
        "badge_id": "farm_tool_collector",
        "name": "Tool Collector",
        "description": "Own at least one of every farm tool kind.",
        "icon": "\U0001FAB5",
        "category": "farming",
        "requirement": {"trigger": "farm_tool_collected_all", "count": 1},
        "reward_usd": 250.0,
        "sort_order": 203,
    },
    {
        "badge_id": "farm_tool_master",
        "name": "Masterwork Farmer",
        "description": "Own every farm tool at masterwork tier.",
        "icon": "\U00002604",
        "category": "farming",
        "requirement": {"trigger": "farm_tool_masterwork_all", "count": 1},
        "reward_usd": 2500.0,
        "sort_order": 204,
    },
    {
        "badge_id": "farm_perk_pinnacle",
        "name": "Pinnacle Perk",
        "description": "Unlock the Lv. 50 Mythic Thumb perk.",
        "icon": "\U0001F30C",
        "category": "farming",
        "requirement": {"trigger": "farm_perk_unlocked_mythic_thumb", "count": 1},
        "reward_usd": 5000.0,
        "sort_order": 205,
    },
    {
        "badge_id": "farm_sunheart_grower",
        "name": "Sunheart Grower",
        "description": "Harvest one Sunheart fruit.",
        "icon": "\U0001F31E",
        "category": "farming",
        "requirement": {"trigger": "farm_harvest_sunheart", "count": 1},
        "reward_usd": 1000.0,
        "sort_order": 206,
    },
    {
        "badge_id": "farm_locust_king_slayer",
        "name": "Locust King Slayer",
        "description": "Defeat the Locust King boss pest.",
        "icon": "\U0001F451",
        "category": "farming",
        "requirement": {"trigger": "farm_pest_kill_locust_king", "count": 1},
        "reward_usd": 800.0,
        "sort_order": 207,
    },
    {
        "badge_id": "farm_crop_wraith_slayer",
        "name": "Wraith Reaper",
        "description": "Defeat the Crop Wraith boss pest.",
        "icon": "\U0001F47B",
        "category": "farming",
        "requirement": {"trigger": "farm_pest_kill_crop_wraith", "count": 1},
        "reward_usd": 4000.0,
        "sort_order": 208,
    },
    {
        "badge_id": "fish_monster_first",
        "name": "First Monster",
        "description": "Defeat your first sea monster on a cast.",
        "icon": "\U0001F419",
        "category": "fishing",
        "requirement": {"trigger": "fish_monster_kill", "count": 1},
        "reward_usd": 500.0,
        "sort_order": 220,
    },
    {
        "badge_id": "fish_monster_slayer",
        "name": "Monster Slayer",
        "description": "Defeat 10 sea monsters.",
        "icon": "\U0001F4AB",
        "category": "fishing",
        "requirement": {"trigger": "fish_monster_kill", "count": 10},
        "reward_usd": 5000.0,
        "sort_order": 221,
    },
    {
        "badge_id": "fish_augmented",
        "name": "Augmented",
        "description": "Own at least one of each rod augment kind (line, lure, reel).",
        "icon": "\U00002728",
        "category": "fishing",
        "requirement": {"trigger": "fish_augment_full_set", "count": 1},
        "reward_usd": 1000.0,
        "sort_order": 222,
    },
    {
        "badge_id": "fish_legendary_diver",
        "name": "Legendary Diver",
        "description": "Catch a zone-locked legendary fish.",
        "icon": "\U0001F3C6",
        "category": "fishing",
        "requirement": {"trigger": "fish_zone_locked_caught", "count": 1},
        "reward_usd": 3000.0,
        "sort_order": 223,
    },
    {
        "badge_id": "fish_tournament_winner",
        "name": "Tournament Champion",
        "description": "Place top 3 in a weekly fishing tournament.",
        "icon": "\U0001F947",
        "category": "fishing",
        "requirement": {"trigger": "fish_tournament_podium", "count": 1},
        "reward_usd": 5000.0,
        "sort_order": 224,
    },
    {
        "badge_id": "delve_arena_first_win",
        "name": "Arena Initiate",
        "description": "Win your first delve arena fight.",
        "icon": "\U00002694",
        "category": "dungeon",
        "requirement": {"trigger": "delve_arena_win", "count": 1},
        "reward_usd": 100.0,
        "sort_order": 240,
    },
    {
        "badge_id": "delve_arena_silver",
        "name": "Silver Delver",
        "description": "Reach Silver rank in the delve arena.",
        "icon": "\U0001F948",
        "category": "dungeon",
        "requirement": {"trigger": "delve_arena_rank_silver", "count": 1},
        "reward_usd": 750.0,
        "sort_order": 241,
    },
    {
        "badge_id": "delve_arena_gold",
        "name": "Gold Delver",
        "description": "Reach Gold rank in the delve arena.",
        "icon": "\U0001F947",
        "category": "dungeon",
        "requirement": {"trigger": "delve_arena_rank_gold", "count": 1},
        "reward_usd": 3000.0,
        "sort_order": 242,
    },
    {
        "badge_id": "delve_arena_rune",
        "name": "Rune Delver",
        "description": "Reach Rune rank in the delve arena.",
        "icon": "\U0001FAA8",
        "category": "dungeon",
        "requirement": {"trigger": "delve_arena_rank_rune", "count": 1},
        "reward_usd": 12000.0,
        "sort_order": 243,
    },
    {
        "badge_id": "delve_arena_streak_3",
        "name": "Hat-Trick",
        "description": "Win 3 delve arena fights in a row.",
        "icon": "\U0001F525",
        "category": "dungeon",
        "requirement": {"trigger": "delve_arena_streak_3", "count": 1},
        "reward_usd": 300.0,
        "sort_order": 244,
    },
    {
        "badge_id": "delve_arena_streak_10",
        "name": "Unbeaten",
        "description": "Win 10 delve arena fights in a row.",
        "icon": "\U0001F31F",
        "category": "dungeon",
        "requirement": {"trigger": "delve_arena_streak_10", "count": 1},
        "reward_usd": 2500.0,
        "sort_order": 245,
    },
    {
        "badge_id": "delve_arena_flawless",
        "name": "Flawless Victory",
        "description": "Win a delve arena fight without taking damage.",
        "icon": "\U00002728",
        "category": "dungeon",
        "requirement": {"trigger": "delve_arena_flawless", "count": 1},
        "reward_usd": 750.0,
        "sort_order": 246,
    },
    {
        "badge_id": "delve_arena_wins_50",
        "name": "Arena Veteran",
        "description": "Win 50 delve arena fights.",
        "icon": "\U0001F396",
        "category": "dungeon",
        "requirement": {"trigger": "delve_arena_win", "count": 50},
        "reward_usd": 2000.0,
        "sort_order": 247,
    },
    {
        "badge_id": "delve_arena_wins_250",
        "name": "Arena Champion",
        "description": "Win 250 delve arena fights.",
        "icon": "\U0001F3C6",
        "category": "dungeon",
        "requirement": {"trigger": "delve_arena_win", "count": 250},
        "reward_usd": 10000.0,
        "sort_order": 248,
    },

    # ── Sage Network ─────────────────────────────────────────────────────
    {
        "badge_id": "sage_first_correct",
        "name": "Apprentice",
        "description": "Answer your first Sage question correctly.",
        "icon": "\U0001F4DD",
        "category": "sage",
        "requirement": {"trigger": "sage_correct", "count": 1},
        "reward_usd": 25.0,
        "sort_order": 260,
    },
    {
        "badge_id": "sage_century",
        "name": "Scholar",
        "description": "Answer 100 Sage questions correctly across any games.",
        "icon": "\U0001F4DA",
        "category": "sage",
        "requirement": {"trigger": "sage_correct", "count": 100},
        "reward_usd": 500.0,
        "sort_order": 261,
    },
    {
        "badge_id": "sage_streak_10",
        "name": "Hot Streak",
        "description": "Score 10 in a single Sage run.",
        "icon": "\U0001F525",
        "category": "sage",
        "requirement": {"trigger": "sage_streak_10", "count": 1},
        "reward_usd": 250.0,
        "sort_order": 262,
    },
    {
        "badge_id": "sage_streak_25",
        "name": "Chart Wizard",
        "description": "Score 25 in a single Sage run.",
        "icon": "\U0001F9D9",
        "category": "sage",
        "requirement": {"trigger": "sage_streak_25", "count": 1},
        "reward_usd": 1500.0,
        "sort_order": 263,
    },
    {
        "badge_id": "sage_triathlete",
        "name": "Triathlete",
        "description": "Finish at least one run in all three Sage games.",
        "icon": "\U0001F3C5",
        "category": "sage",
        "requirement": {"trigger": "sage_triathlete", "count": 1},
        "reward_usd": 750.0,
        "sort_order": 264,
    },
]


def get(badge_id: str) -> dict | None:
    """Return the catalog entry for ``badge_id`` or ``None`` if missing."""
    for a in ACHIEVEMENTS:
        if a["badge_id"] == badge_id:
            return a
    return None


def by_trigger(trigger: str) -> list[dict]:
    """Return all achievements whose requirement.trigger matches ``trigger``."""
    return [a for a in ACHIEVEMENTS if a["requirement"].get("trigger") == trigger]


def by_category(category: str) -> list[dict]:
    """Return all achievements in ``category`` sorted by ``sort_order``."""
    out = [a for a in ACHIEVEMENTS if a["category"] == category]
    out.sort(key=lambda a: a.get("sort_order", 0))
    return out


def all_ids() -> set[str]:
    """Return the set of every known badge_id. Used for integrity checks."""
    return {a["badge_id"] for a in ACHIEVEMENTS}
