"""Quest catalog - templates for daily and weekly rotating quests.

Each template is one concrete quest a user can be assigned for a period.
services/quests.py draws from the appropriate period pool on assignment
and tracks progress as bus events fire through the same trigger labels
as achievements_config.py.

Schema:
    quest_id      - stable id. Never rename.
    name          - short display name.
    description   - one-line blurb shown in the quest card.
    period        - 'daily' or 'weekly'.
    trigger       - logical trigger label (see services/achievements.py).
    target        - integer threshold to complete.
    reward_usd    - USD paid to wallet on claim.
    icon          - single emoji.

The filter field (optional) lets a template key on event payload. The
quests service forwards the event kwargs so handlers can inspect
fields like won=True for gamble/exploit wins.
"""
from __future__ import annotations

DAILY_SLOTS: int = 3
WEEKLY_SLOTS: int = 2

QUESTS: list[dict] = [
    # ── Daily pool ────────────────────────────────────────────────────────
    {
        "quest_id": "d_work_3",
        "name": "Clock In",
        "description": "Complete 3 work shifts today.",
        "period": "daily",
        "trigger": "work_completed",
        "target": 3,
        "reward_usd": 150.0,
        "icon": "\U0001F4BC",
    },
    {
        "quest_id": "d_trades_3",
        "name": "Active Trader",
        "description": "Execute 8 trades today.",
        "period": "daily",
        "trigger": "trade_executed",
        "target": 8,
        "reward_usd": 200.0,
        "icon": "\U0001F4C8",
    },
    {
        "quest_id": "d_swap_1",
        "name": "Swap It Up",
        "description": "Use a pool swap 3 times today.",
        "period": "daily",
        "trigger": "swap_executed",
        "target": 3,
        "reward_usd": 120.0,
        "icon": "\U0001F501",
    },
    {
        "quest_id": "d_gamble_5",
        "name": "Feeling Lucky",
        "description": "Play 15 games today.",
        "period": "daily",
        "trigger": "gamble_play",
        "target": 15,
        "reward_usd": 150.0,
        "icon": "\U0001F3B2",
    },
    {
        "quest_id": "d_mine_1",
        "name": "Get A Block",
        "description": "Earn 3 mining payouts today.",
        "period": "daily",
        "trigger": "block_mined",
        "target": 3,
        "reward_usd": 120.0,
        "icon": "\U000026CF",
    },
    {
        "quest_id": "d_daily_1",
        "name": "Check In",
        "description": "Claim your daily reward.",
        "period": "daily",
        "trigger": "daily_claimed",
        "target": 1,
        "reward_usd": 75.0,
        "icon": "\U0001F4C5",
    },
    {
        "quest_id": "d_deposit_1",
        "name": "Safe Keeping",
        "description": "Make 3 bank deposits today.",
        "period": "daily",
        "trigger": "bank_deposit",
        "target": 3,
        "reward_usd": 100.0,
        "icon": "\U0001F3E6",
    },
    {
        "quest_id": "d_exploit_1",
        "name": "Try An Exploit",
        "description": "Run 3 exploits today.",
        "period": "daily",
        "trigger": "exploit_run",
        "target": 3,
        "reward_usd": 100.0,
        "icon": "\U0001F480",
    },
    {
        "quest_id": "d_buddy_win_1",
        "name": "Buddy Bout",
        "description": "Win 2 buddy battles today.",
        "period": "daily",
        "trigger": "buddy_battle_win",
        "target": 2,
        "reward_usd": 125.0,
        "icon": "\U0001F94A",
    },
    {
        "quest_id": "d_buddy_wins_3",
        "name": "Triple Threat",
        "description": "Win 7 buddy battles today.",
        "period": "daily",
        "trigger": "buddy_battle_win",
        "target": 7,
        "reward_usd": 250.0,
        "icon": "\U0001F3C6",
    },
    {
        "quest_id": "d_buddy_adopt_1",
        "name": "Open Your Home",
        "description": "Adopt a buddy today.",
        "period": "daily",
        "trigger": "buddy_adopted",
        "target": 1,
        "reward_usd": 150.0,
        "icon": "\U0001F436",
    },
    {
        "quest_id": "d_exploit_win_1",
        "name": "Eat the Rich",
        "description": "Eat 2 rich players today.",
        "period": "daily",
        "trigger": "exploit_win",
        "target": 2,
        "reward_usd": 175.0,
        "icon": "\U0001F3F4",
    },
    {
        "quest_id": "d_chat_level_1",
        "name": "Level Up",
        "description": "Reach a new chat level today.",
        "period": "daily",
        "trigger": "chat_level_up",
        "target": 1,
        "reward_usd": 125.0,
        "icon": "\U0001F4AC",
    },
    {
        "quest_id": "d_fish_3",
        "name": "Hooked",
        "description": "Catch 10 fish today.",
        "period": "daily",
        "trigger": "fish_caught",
        "target": 10,
        "reward_usd": 150.0,
        "icon": "\U0001F3A3",
    },
    {
        "quest_id": "d_fish_legend_1",
        "name": "Trophy Day",
        "description": "Land a Legendary fish today.",
        "period": "daily",
        "trigger": "fish_legendary",
        "target": 1,
        "reward_usd": 1000.0,
        "icon": "\U0001F3C6",
    },
    {
        "quest_id": "d_lure_swap_1",
        "name": "Cycle the Tackle",
        "description": "Burn LURE for REEL 3 times today.",
        "period": "daily",
        "trigger": "fish_lure_swap",
        "target": 3,
        "reward_usd": 200.0,
        "icon": "\U0001F501",
    },
    {
        "quest_id": "d_reel_cashout_1",
        "name": "Cash Out",
        "description": "Burn REEL for USD 2 times today.",
        "period": "daily",
        "trigger": "fish_reel_cashout",
        "target": 2,
        "reward_usd": 300.0,
        "icon": "\U0001F4B5",
    },
    {
        "quest_id": "d_wild_win_1",
        "name": "Hooked Something Toothy",
        "description": "Win 3 wild-buddy battles from casts today.",
        "period": "daily",
        "trigger": "fish_wild_battle_won",
        "target": 3,
        "reward_usd": 750.0,
        "icon": "\U00002694",
    },

    # ── Weekly pool ───────────────────────────────────────────────────────
    {
        "quest_id": "w_trades_25",
        "name": "Market Maker",
        "description": "Execute 25 trades this week.",
        "period": "weekly",
        "trigger": "trade_executed",
        "target": 25,
        "reward_usd": 1500.0,
        "icon": "\U0001F4CA",
    },
    {
        "quest_id": "w_mine_15",
        "name": "Week of Hashing",
        "description": "Earn 15 mining payouts this week.",
        "period": "weekly",
        "trigger": "block_mined",
        "target": 15,
        "reward_usd": 1500.0,
        "icon": "\U0001F525",
    },
    {
        "quest_id": "w_lp_2",
        "name": "Liquidity Party",
        "description": "Add liquidity twice this week.",
        "period": "weekly",
        "trigger": "lp_added",
        "target": 2,
        "reward_usd": 1200.0,
        "icon": "\U0001F9EA",
    },
    {
        "quest_id": "w_gamble_wins_5",
        "name": "Hot Hand",
        "description": "Win 5 games this week.",
        "period": "weekly",
        "trigger": "gamble_win",
        "target": 5,
        "reward_usd": 1000.0,
        "icon": "\U0001F340",
    },
    {
        "quest_id": "w_work_15",
        "name": "Full Week Shift",
        "description": "Complete 15 work shifts this week.",
        "period": "weekly",
        "trigger": "work_completed",
        "target": 15,
        "reward_usd": 1200.0,
        "icon": "\U0001F6E0",
    },
    {
        "quest_id": "w_stake_1",
        "name": "Stake A Position",
        "description": "Open a new stake this week.",
        "period": "weekly",
        "trigger": "stake_created",
        "target": 1,
        "reward_usd": 800.0,
        "icon": "\U0001F4CC",
    },
    {
        "quest_id": "w_buddy_wins_3",
        "name": "Champion Of The Week",
        "description": "Win 3 buddy battles this week.",
        "period": "weekly",
        "trigger": "buddy_battle_win",
        "target": 3,
        "reward_usd": 1000.0,
        "icon": "\U0001F3C5",
    },
    {
        "quest_id": "w_buddy_wins_15",
        "name": "Arena Dominator",
        "description": "Win 15 buddy battles this week.",
        "period": "weekly",
        "trigger": "buddy_battle_win",
        "target": 15,
        "reward_usd": 2500.0,
        "icon": "\U0001F5E1",
    },
    {
        "quest_id": "w_buddy_adopt_2",
        "name": "Shelter Rescuer",
        "description": "Adopt 2 buddies this week.",
        "period": "weekly",
        "trigger": "buddy_adopted",
        "target": 2,
        "reward_usd": 800.0,
        "icon": "\U0001F6CF",
    },
    {
        "quest_id": "w_exploit_wins_3",
        "name": "Week Of Class War",
        "description": "Eat 3 rich players this week.",
        "period": "weekly",
        "trigger": "exploit_win",
        "target": 3,
        "reward_usd": 1200.0,
        "icon": "\U0001F3F4",
    },
    {
        "quest_id": "w_fish_25",
        "name": "Reel Week",
        "description": "Catch 25 fish this week.",
        "period": "weekly",
        "trigger": "fish_caught",
        "target": 25,
        "reward_usd": 1500.0,
        "icon": "\U0001F3A3",
    },
    {
        "quest_id": "w_fish_legend_2",
        "name": "Trophy Wall",
        "description": "Land 2 Legendary fish this week.",
        "period": "weekly",
        "trigger": "fish_legendary",
        "target": 2,
        "reward_usd": 5000.0,
        "icon": "\U0001F3C5",
    },
    {
        "quest_id": "w_lure_stake_3",
        "name": "Long Cast",
        "description": "Stake LURE 3 times this week. Patience pays in REEL.",
        "period": "weekly",
        "trigger": "fish_lure_stake",
        "target": 3,
        "reward_usd": 2500.0,
        "icon": "\U0001F510",
    },
    {
        "quest_id": "w_reel_cashout_5",
        "name": "Pier Pressure",
        "description": "Burn REEL for USD 5 times this week.",
        "period": "weekly",
        "trigger": "fish_reel_cashout",
        "target": 5,
        "reward_usd": 4000.0,
        "icon": "\U0001F4B5",
    },
    {
        "quest_id": "w_wild_wins_5",
        "name": "Aquatic Gauntlet",
        "description": "Win 5 wild-buddy battles from casts this week.",
        "period": "weekly",
        "trigger": "fish_wild_battle_won",
        "target": 5,
        "reward_usd": 6_000.0,
        "icon": "\U00002694",
    },
    {
        "quest_id": "w_wild_capture_1",
        "name": "Catch a Live One",
        "description": "Capture a wild aquatic buddy this week.",
        "period": "weekly",
        "trigger": "fish_wild_buddy_captured",
        "target": 1,
        "reward_usd": 8_000.0,
        "icon": "\U0001F578",
    },

    # ---- Dungeon (Delve crawler) ---------------------------------------
    {
        "quest_id": "d_delve_kills_5",
        "name": "Crawl Day",
        "description": "Slay 5 dungeon mobs today.",
        "period": "daily",
        "trigger": "delve_kill",
        "target": 5,
        "reward_usd": 200.0,
        "icon": "\U00002694",
    },
    {
        "quest_id": "d_delve_mine_3",
        "name": "Pickaxe Day",
        "description": "Mine 3 ore veins today.",
        "period": "daily",
        "trigger": "delve_mine",
        "target": 3,
        "reward_usd": 150.0,
        "icon": "\U000026CF",
    },
    {
        "quest_id": "d_delve_capture_1",
        "name": "Tame a Beastie",
        "description": "Capture a dungeon buddy today.",
        "period": "daily",
        "trigger": "delve_capture",
        "target": 1,
        "reward_usd": 250.0,
        "icon": "\U0001F9F2",
    },
    {
        "quest_id": "w_delve_boss_1",
        "name": "Boss Hunter",
        "description": "Defeat a dungeon boss this week.",
        "period": "weekly",
        "trigger": "delve_boss_kill",
        "target": 1,
        "reward_usd": 5_000.0,
        "icon": "\U0001F47E",
    },
    {
        "quest_id": "w_delve_floor_5",
        "name": "Deep Diver",
        "description": "Reach Floor 5 or deeper this week.",
        "period": "weekly",
        "trigger": "delve_floor_reached",
        "target": 5,
        "reward_usd": 4_000.0,
        "icon": "\U0001F6AA",
    },

    # ---- Crafting (Forge Network) --------------------------------------
    {
        "quest_id": "d_craft_make_3",
        "name": "Forge Day",
        "description": "Craft 3 items today with `,craft make`.",
        "period": "daily",
        "trigger": "craft_made",
        "target": 3,
        "reward_usd": 200.0,
        "icon": "\U0001F528",
    },
    {
        "quest_id": "d_craft_apply_1",
        "name": "Field Test",
        "description": "Apply a crafted item back into a game today.",
        "period": "daily",
        "trigger": "craft_applied",
        "target": 1,
        "reward_usd": 150.0,
        "icon": "\U0001F503",
    },
    {
        "quest_id": "w_craft_make_15",
        "name": "Smith Week",
        "description": "Craft 15 items this week.",
        "period": "weekly",
        "trigger": "craft_made",
        "target": 15,
        "reward_usd": 1_500.0,
        "icon": "\U0001F528",
    },
    {
        "quest_id": "w_craft_legendary_1",
        "name": "Masterwork",
        "description": "Craft a legendary recipe this week.",
        "period": "weekly",
        "trigger": "craft_legendary",
        "target": 1,
        "reward_usd": 5_000.0,
        "icon": "\U00002728",
    },

    # ---- Dungeon wild buddy battles ------------------------------------
    {
        "quest_id": "d_delve_wild_win_1",
        "name": "Cave Brawl",
        "description": "Win a wild-buddy battle in a delve today.",
        "period": "daily",
        "trigger": "delve_wild_battle_won",
        "target": 1,
        "reward_usd": 250.0,
        "icon": "\U0001F4AB",
    },
    {
        "quest_id": "w_delve_wild_capture_1",
        "name": "Tame the Depths",
        "description": "Capture a wild buddy in a delve this week.",
        "period": "weekly",
        "trigger": "delve_wild_buddy_captured",
        "target": 1,
        "reward_usd": 3_000.0,
        "icon": "\U0001F49E",
    },
    # ── Buddy storage / breeding (daily + weekly) ─────────────────────────
    {
        "quest_id": "d_buddy_store_1",
        "name": "Reorganise the Computer",
        "description": "Stash one buddy in storage today.",
        "period": "daily",
        "trigger": "buddy_stored",
        "target": 1,
        "reward_usd": 100.0,
        "icon": "\U0001F4E6",
    },
    {
        "quest_id": "w_daycare_collect_1",
        "name": "Hatchery Run",
        "description": "Collect a nest egg this week.",
        "period": "weekly",
        "trigger": "daycare_egg_collected",
        "target": 1,
        "reward_usd": 1500.0,
        "icon": "\U0001F423",
    },
    {
        "quest_id": "w_daycare_collect_3",
        "name": "Champion Breeder",
        "description": "Collect 3 nest eggs this week.",
        "period": "weekly",
        "trigger": "daycare_egg_collected",
        "target": 3,
        "reward_usd": 5000.0,
        "icon": "\U0001F423",
    },
    # ── Crafting specialties (daily + weekly) ─────────────────────────────
    {
        "quest_id": "d_specialty_up_1",
        "name": "Sharpen a Skill",
        "description": "Level up any crafting specialty today.",
        "period": "daily",
        "trigger": "specialty_level_up",
        "target": 1,
        "reward_usd": 250.0,
        "icon": "\U0001F4DA",
    },
    {
        "quest_id": "w_specialty_up_3",
        "name": "Steady Practice",
        "description": "Level up crafting specialties 3 times this week.",
        "period": "weekly",
        "trigger": "specialty_level_up",
        "target": 3,
        "reward_usd": 1500.0,
        "icon": "\U0001F4DA",
    },

    # ── Expeditions (daily + weekly) ──────────────────────────────────────
    # ,expedition surfaces a passive-but-engaged loop: send the active
    # buddy, come back later, collect loot. Quests reward both halves so
    # players who only check in twice a day still progress.
    {
        "quest_id": "d_expedition_send_1",
        "name": "Pack a Lunch",
        "description": "Send 1 buddy expedition today.",
        "period": "daily",
        "trigger": "expedition_started",
        "target": 1,
        "reward_usd": 200.0,
        "icon": "\U0001F392",
    },
    {
        "quest_id": "d_expedition_collect_2",
        "name": "Welcome Home",
        "description": "Collect 2 finished expeditions today.",
        "period": "daily",
        "trigger": "expedition_collected",
        "target": 2,
        "reward_usd": 350.0,
        "icon": "\U0001F381",
    },
    {
        "quest_id": "w_expedition_collect_5",
        "name": "Frequent Flyer",
        "description": "Collect 5 expeditions this week.",
        "period": "weekly",
        "trigger": "expedition_collected",
        "target": 5,
        "reward_usd": 2000.0,
        "icon": "\U0001F392",
    },
    {
        "quest_id": "w_expedition_reef_1",
        "name": "Salt and Coral",
        "description": "Complete 1 Coral Reef expedition this week.",
        "period": "weekly",
        "trigger": "expedition_collected_reef",
        "target": 1,
        "reward_usd": 750.0,
        "icon": "\U0001FAB8",
    },
    {
        "quest_id": "w_expedition_ruins_1",
        "name": "Whisper of Ruins",
        "description": "Complete 1 Ancient Ruins expedition this week.",
        "period": "weekly",
        "trigger": "expedition_collected_ruins",
        "target": 1,
        "reward_usd": 1200.0,
        "icon": "\U0001F3DB",
    },

    # ── Class-flavored daily quests (added with archer + druid) ──────────
    {
        "quest_id": "d_volley_3",
        "name": "Loose A Volley",
        "description": "Cast Volley 3 times today (Archer skill).",
        "period": "daily",
        "trigger": "delve_skill_volley",
        "target": 3,
        "reward_usd": 200.0,
        "icon": "\U0001F3F9",
    },
    {
        "quest_id": "d_wildshape_3",
        "name": "Wild At Heart",
        "description": "Trigger Wildshape 3 times today (Druid skill).",
        "period": "daily",
        "trigger": "delve_skill_wildshape",
        "target": 3,
        "reward_usd": 200.0,
        "icon": "\U0001F33F",
    },
    {
        "quest_id": "d_arrows_craft_1",
        "name": "Quiver Stocked",
        "description": "Craft 5 arrow or bolt bundles today.",
        "period": "daily",
        "trigger": "craft_ammo",
        "target": 5,
        "reward_usd": 120.0,
        "icon": "\U0001F3F9",
    },
    {
        "quest_id": "d_delve_upgrade_1",
        "name": "Sharpen Up",
        "description": "Spend at least 1 stat point in `,delve upgrade` today.",
        "period": "daily",
        "trigger": "delve_stat_spent",
        "target": 1,
        "reward_usd": 90.0,
        "icon": "\U0001F4CA",
    },
    {
        "quest_id": "d_class_reroll_1",
        "name": "Reinvent Yourself",
        "description": "Reroll your delve class today.",
        "period": "daily",
        "trigger": "delve_class_reroll",
        "target": 1,
        "reward_usd": 250.0,
        "icon": "\U0001F504",
    },

    # ── Class-flavored weekly quests ─────────────────────────────────────
    {
        "quest_id": "w_archer_kills_25",
        "name": "Marksman",
        "description": "Slay 25 mobs as an Archer this week.",
        "period": "weekly",
        "trigger": "delve_kill_archer",
        "target": 25,
        "reward_usd": 1500.0,
        "icon": "\U0001F3F9",
    },
    {
        "quest_id": "w_druid_captures_3",
        "name": "Speak To The Wild",
        "description": "Capture 3 mobs as a Druid this week.",
        "period": "weekly",
        "trigger": "delve_capture_druid",
        "target": 3,
        "reward_usd": 1500.0,
        "icon": "\U0001F33F",
    },

    # ── Sage Network quests ──────────────────────────────────────────────
    {
        "quest_id": "d_sage_correct_10",
        "name": "Quick Study",
        "description": "Answer 10 Sage questions correctly today.",
        "period": "daily",
        "trigger": "sage_correct",
        "target": 10,
        "reward_usd": 200.0,
        "icon": "\U0001F4DA",
    },
    {
        "quest_id": "d_sage_runs_3",
        "name": "Pop Quiz",
        "description": "Finish 3 Sage runs today (any of pattern / gauge / tknom).",
        "period": "daily",
        "trigger": "sage_run_finished",
        "target": 3,
        "reward_usd": 250.0,
        "icon": "\U0001F393",
    },
    {
        "quest_id": "w_sage_correct_50",
        "name": "Chart Reader",
        "description": "Answer 50 Sage questions correctly this week.",
        "period": "weekly",
        "trigger": "sage_correct",
        "target": 50,
        "reward_usd": 1500.0,
        "icon": "\U0001F4C8",
    },
]


def by_period(period: str) -> list[dict]:
    """Return all quest templates for ``period`` ('daily' or 'weekly')."""
    return [q for q in QUESTS if q["period"] == period]


def get(quest_id: str) -> dict | None:
    """Return the template for ``quest_id`` or ``None`` if missing."""
    for q in QUESTS:
        if q["quest_id"] == quest_id:
            return q
    return None


def by_trigger(trigger: str) -> list[dict]:
    """Return all quest templates whose trigger matches ``trigger``."""
    return [q for q in QUESTS if q["trigger"] == trigger]
